services:
  - type: web
    name: student-attendance-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/db/all
    autoDeploy: true
